name: Multi-Stage Deployment

on:
  push:
    branches:
      - main
      - envs
  workflow_dispatch:

jobs:
  initialization:
    uses: wuerzelchen/ReusableWorkflows/.github/workflows/initialize.yaml@main
  
  plan:
    needs: initialization
    uses: wuerzelchen/ReusableWorkflows/.github/workflows/plan.yaml@main
    with:
      environment: ${{ github.ref_name }}
  
  deploy:
    environment: ${{ github.ref_name }}
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ${{ github.ref_name }} Environment
        run: |
          echo "Deploying to ${{ needs.plan.outputs.environment }} environment..."
          # Add your PROD deployment commands
          echo "PROD Deployment complete."
